version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8000:1234"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      MONGODB_URI: mongodb://mongo:27017/productdb
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"